// This file was autogenerated by ./build/depswriter.py.
// Please do not edit.
goog.addDependency('components/map/MapDirective.js', ['erds_map_directive'], []);
goog.addDependency('components/map/MapModule.js', ['erds_map'], ['erds_map_service']);
goog.addDependency('components/map/MapService.js', ['erds_map_service'], []);
goog.addDependency('js/MapController.js', ['erds_map_controller'], []);
goog.addDependency('js/erds.js', ['erds'], ['erds_map', 'erds_map_controller']);
