// This file was autogenerated by ./depswriter.py.
// Please do not edit.
goog.addDependency('components/map/MapService.js', ['erds_map_service'], []);
goog.addDependency('components/map/erds_map.js', ['erds_map'], ['erds_map_service']);
goog.addDependency('js/MainController.js', ['erds_main_controller'], []);
goog.addDependency('js/erds.js', ['erds'], ['erds_main_controller', 'erds_map']);
